stages:
  - build
  - deploy

image: docker:24.0.5
services:
  - docker:24.0.5-dind

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_TLS_CERTDIR: ""

builder:
  stage: build
  only:
    - main
  script:
    - docker build -t hello:gitlab-$CI_COMMIT_SHORT_SHA .
  except:
    - main

deployer:
  stage: deploy
  script:
    - docker build -t hello:gitlab-$CI_COMMIT_SHORT_SHA .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push hello:gitlab-$CI_COMMIT_SHORT_SHA
  only:
    - main